import { PlayerStats } from '@/types/player';

export const mockHornetsData: PlayerStats[] = [
  {
    playerId: 1,
    player: {
      id: 1,
      first_name: 'LaMelo',
      last_name: 'Ball',
      position: 'PG',
      height: '6-7',
      weight: '180',
      jersey_number: '1',
      college: 'N/A'
    },
    season: 2024,
    gamesPlayed: 72,
    pointsPerGame: 23.9,
    rebounds: 6.2,
    assists: 8.0,
    fieldGoalPercentage: 0.431,
    threePointPercentage: 0.358,
    freeThrowPercentage: 0.874,
    minutesPlayed: 34.1,
    steals: 1.8,
    blocks: 0.2,
    turnovers: 3.4
  },
  {
    playerId: 2,
    player: {
      id: 2,
      first_name: 'Terry',
      last_name: 'Rozier',
      position: 'SG',
      height: '6-1',
      weight: '190',
      jersey_number: '3',
      college: 'Louisville'
    },
    season: 2024,
    gamesPlayed: 68,
    pointsPerGame: 21.4,
    rebounds: 4.6,
    assists: 4.2,
    fieldGoalPercentage: 0.439,
    threePointPercentage: 0.371,
    freeThrowPercentage: 0.823,
    minutesPlayed: 35.2,
    steals: 1.1,
    blocks: 0.4,
    turnovers: 2.8
  },
  {
    playerId: 3,
    player: {
      id: 3,
      first_name: 'Gordon',
      last_name: 'Hayward',
      position: 'SF',
      height: '6-7',
      weight: '225',
      jersey_number: '20',
      college: 'Butler'
    },
    season: 2024,
    gamesPlayed: 51,
    pointsPerGame: 14.7,
    rebounds: 4.1,
    assists: 4.6,
    fieldGoalPercentage: 0.466,
    threePointPercentage: 0.315,
    freeThrowPercentage: 0.847,
    minutesPlayed: 28.2,
    steals: 1.2,
    blocks: 0.3,
    turnovers: 2.3
  },
  {
    playerId: 4,
    player: {
      id: 4,
      first_name: 'Miles',
      last_name: 'Bridges',
      position: 'PF',
      height: '6-7',
      weight: '225',
      jersey_number: '0',
      college: 'Michigan State'
    },
    season: 2024,
    gamesPlayed: 69,
    pointsPerGame: 20.2,
    rebounds: 7.0,
    assists: 3.8,
    fieldGoalPercentage: 0.491,
    threePointPercentage: 0.355,
    freeThrowPercentage: 0.747,
    minutesPlayed: 35.8,
    steals: 1.0,
    blocks: 0.8,
    turnovers: 2.4
  },
  {
    playerId: 5,
    player: {
      id: 5,
      first_name: 'Mason',
      last_name: 'Plumlee',
      position: 'C',
      height: '6-11',
      weight: '254',
      jersey_number: '24',
      college: 'Duke'
    },
    season: 2024,
    gamesPlayed: 73,
    pointsPerGame: 11.1,
    rebounds: 9.3,
    assists: 3.3,
    fieldGoalPercentage: 0.649,
    threePointPercentage: 0.000,
    freeThrowPercentage: 0.576,
    minutesPlayed: 26.9,
    steals: 0.9,
    blocks: 0.8,
    turnovers: 2.1
  },
  {
    playerId: 6,
    player: {
      id: 6,
      first_name: 'Kelly',
      last_name: 'Oubre Jr.',
      position: 'SF',
      height: '6-7',
      weight: '203',
      jersey_number: '12',
      college: 'Kansas'
    },
    season: 2024,
    gamesPlayed: 48,
    pointsPerGame: 16.8,
    rebounds: 5.0,
    assists: 1.3,
    fieldGoalPercentage: 0.493,
    threePointPercentage: 0.329,
    freeThrowPercentage: 0.793,
    minutesPlayed: 32.4,
    steals: 1.1,
    blocks: 0.4,
    turnovers: 1.6
  },
  {
    playerId: 7,
    player: {
      id: 7,
      first_name: 'P.J.',
      last_name: 'Washington',
      position: 'PF',
      height: '6-7',
      weight: '230',
      jersey_number: '25',
      college: 'Kentucky'
    },
    season: 2024,
    gamesPlayed: 65,
    pointsPerGame: 15.2,
    rebounds: 5.5,
    assists: 2.4,
    fieldGoalPercentage: 0.444,
    threePointPercentage: 0.367,
    freeThrowPercentage: 0.713,
    minutesPlayed: 31.9,
    steals: 1.1,
    blocks: 0.9,
    turnovers: 1.8
  },
  {
    playerId: 8,
    player: {
      id: 8,
      first_name: 'Mark',
      last_name: 'Williams',
      position: 'C',
      height: '7-0',
      weight: '242',
      jersey_number: '5',
      college: 'Duke'
    },
    season: 2024,
    gamesPlayed: 42,
    pointsPerGame: 9.7,
    rebounds: 7.3,
    assists: 1.3,
    fieldGoalPercentage: 0.672,
    threePointPercentage: 0.000,
    freeThrowPercentage: 0.636,
    minutesPlayed: 22.1,
    steals: 0.6,
    blocks: 1.1,
    turnovers: 1.4
  }
];