name: Ingest NBA Stats

on:
  schedule:
    # Run daily at 07:15 UTC (adjust as desired)
    - cron: "15 7 * * *"
  workflow_dispatch:
    inputs:
      season:
        description: "NBA season start year (e.g., 2024)"
        required: false
        type: string
      team:
        description: "Team abbreviation (e.g., CHA)"
        required: false
        type: string

jobs:
  ingest:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    concurrency:
      group: ingest-nba-stats
      cancel-in-progress: false
    env:
      # Required
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      SUPABASE_SERVICE_ROLE: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

      # Optional: If you experience fetch issues from GH Actions, set these secrets
      NBA_STATS_USER_AGENT: ${{ secrets.NBA_STATS_USER_AGENT }}
      NBA_STATS_REFERER: ${{ secrets.NBA_STATS_REFERER }}
      NBA_STATS_ORIGIN: ${{ secrets.NBA_STATS_ORIGIN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Compute season (if not provided)
        id: season
        run: |
          if [ -n "${{ github.event.inputs.season }}" ]; then
            echo "SEASON=${{ github.event.inputs.season }}" >> $GITHUB_ENV
          else
            YEAR=$(date +%Y)
            MON=$(date +%m)
            if [ "$MON" -ge 10 ]; then SEASON=$YEAR; else SEASON=$((YEAR-1)); fi
            echo "SEASON=$SEASON" >> $GITHUB_ENV
          fi

      - name: Compute team (if not provided)
        run: |
          if [ -n "${{ github.event.inputs.team }}" ]; then
            echo "TEAM=${{ github.event.inputs.team }}" >> $GITHUB_ENV
          else
            echo "TEAM=CHA" >> $GITHUB_ENV
          fi

      - name: Run ingestion
        run: node scripts/ingest-nba-stats.mjs "$SEASON" "$TEAM"
